name: spm

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  spm:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v4
    - name: Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
    - name: Build
      run: swift build
